name: Ubuntu

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Deploy with Docker Compose
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Test container deployment
        run: docker-compose -f compose.yml up -d
